name: Build and deploy ASP.Net Core app to Azure Web App - storkdorkapp

env:
  AZURE_WEBAPP_PACKAGE_PATH: '${{ github.workspace }}/publish'  # New publish path
  DOTNET_VERSION: '8.0'
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish .NET Core app
        run: dotnet publish storkdork/StorkDorkMain/StorkDork.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./published

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'storkdorkapp'
          slot-name: 'Production'
          package: ./published 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_681CB4666C77411A948188E1E890D326 }}
